// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Distinguishes the agent blueprint object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentBlueprintObject
    {
        [EnumMember(Value = "agent_blueprint")]
        #pragma warning disable CS1591
        AgentBlueprint,
        #pragma warning restore CS1591
    }
}
