// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Derived from `revoked_at` and `expires_at` at read time; a revoked session stays `revoked` even after it expires.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentInstanceSessionStatus
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "revoked")]
        #pragma warning disable CS1591
        Revoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "expired")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
    }
}
