// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentTokenValidation : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The delegating user carried in the `act.sub` claim of the token, or `null` for autonomous sessions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActingUserId { get; set; }
#nullable restore
#else
        public string ActingUserId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agent instance the token was minted for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgentInstanceId { get; set; }
#nullable restore
#else
        public string AgentInstanceId { get; set; }
#endif
        /// <summary>The agent instance session backing the token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgentInstanceSessionId { get; set; }
#nullable restore
#else
        public string AgentInstanceSessionId { get; set; }
#endif
        /// <summary>The caller-supplied context echoed into the token at mint time, or `null` when none was given.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Intent { get; set; }
#nullable restore
#else
        public string Intent { get; set; }
#endif
        /// <summary>The organization the agent acts within.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The effective permission slugs carried by the token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Permissions { get; set; }
#nullable restore
#else
        public List<string> Permissions { get; set; }
#endif
        /// <summary>When the backing agent instance session expires.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionExpiresAt { get; set; }
#nullable restore
#else
        public string SessionExpiresAt { get; set; }
#endif
        /// <summary>Always `true`: an invalid token is reported as an error with a stable code, never as a `200`.</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Models.TrueValueValid? Valid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.AgentTokenValidation"/> and sets the default values.
        /// </summary>
        public AgentTokenValidation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.AgentTokenValidation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.WorkOs.OpenApiClient.Models.AgentTokenValidation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.WorkOs.OpenApiClient.Models.AgentTokenValidation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acting_user_id", n => { ActingUserId = n.GetStringValue(); } },
                { "agent_instance_id", n => { AgentInstanceId = n.GetStringValue(); } },
                { "agent_instance_session_id", n => { AgentInstanceSessionId = n.GetStringValue(); } },
                { "intent", n => { Intent = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "permissions", n => { Permissions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "session_expires_at", n => { SessionExpiresAt = n.GetStringValue(); } },
                { "valid", n => { Valid = n.GetEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.TrueValueValid>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("acting_user_id", ActingUserId);
            writer.WriteStringValue("agent_instance_id", AgentInstanceId);
            writer.WriteStringValue("agent_instance_session_id", AgentInstanceSessionId);
            writer.WriteStringValue("intent", Intent);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteCollectionOfPrimitiveValues<string>("permissions", Permissions);
            writer.WriteStringValue("session_expires_at", SessionExpiresAt);
            writer.WriteEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.TrueValueValid>("valid", Valid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
