// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The error code identifying the type of error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApiKeysControllerExpire409Response_code
    {
        [EnumMember(Value = "api_key_already_expired")]
        #pragma warning disable CS1591
        ApiKeyAlreadyExpired,
        #pragma warning restore CS1591
    }
}
