// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuditLogSchemaJson : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The metadata schema for the actor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonActor? Actor { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonActor Actor { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The timestamp when the Audit Log Schema was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Additional data associated with the event or entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonMetadataProperty? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonMetadataProperty Metadata { get; set; }
#endif
        /// <summary>Distinguishes the Audit Log Schema object.</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJson_object? Object { get; set; }
        /// <summary>The list of targets for the schema.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonTargetsItem>? Targets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonTargetsItem> Targets { get; set; }
#endif
        /// <summary>The version of the schema.</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJson"/> and sets the default values.
        /// </summary>
        public AuditLogSchemaJson()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJson"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJson CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJson();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actor", n => { Actor = n.GetObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonActor>(global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonActor.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonMetadataProperty>(global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonMetadataProperty.CreateFromDiscriminatorValue); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJson_object>(); } },
                { "targets", n => { Targets = n.GetCollectionOfObjectValues<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonTargetsItem>(global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonTargetsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonActor>("actor", Actor);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonMetadataProperty>("metadata", Metadata);
            writer.WriteEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJson_object>("object", Object);
            writer.WriteCollectionOfObjectValues<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogSchemaJsonTargetsItem>("targets", Targets);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
