// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Distinguishes the Audit Log Action object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuditLogActionJson_object
    {
        [EnumMember(Value = "audit_log_action")]
        #pragma warning disable CS1591
        Audit_log_action,
        #pragma warning restore CS1591
    }
}
