// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The current state of the Audit Log Stream.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuditLogConfiguration_log_stream_state
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "inactive")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid")]
        #pragma warning disable CS1591
        Invalid,
        #pragma warning restore CS1591
    }
}
