// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>
    /// The Audit Log Stream currently configured for the organization, if any.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuditLogConfiguration_log_stream : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An ISO 8601 timestamp.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Unique identifier of the Audit Log Stream.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>ISO-8601 timestamp of when the last event was successfully synced, or null if no events have been synced.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastSyncedAt { get; set; }
#nullable restore
#else
        public string LastSyncedAt { get; set; }
#endif
        /// <summary>The current state of the Audit Log Stream.</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogConfiguration_log_stream_state? State { get; set; }
        /// <summary>The type of the Audit Log Stream destination.</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogConfiguration_log_stream_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogConfiguration_log_stream"/> and sets the default values.
        /// </summary>
        public AuditLogConfiguration_log_stream()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogConfiguration_log_stream"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogConfiguration_log_stream CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogConfiguration_log_stream();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "last_synced_at", n => { LastSyncedAt = n.GetStringValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogConfiguration_log_stream_state>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogConfiguration_log_stream_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("last_synced_at", LastSyncedAt);
            writer.WriteEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogConfiguration_log_stream_state>("state", State);
            writer.WriteEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.AuditLogConfiguration_log_stream_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
