// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The error code identifying the type of error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuthorizationResourcesByExternalIdControllerUpdateByExternalId400_code
    {
        [EnumMember(Value = "lock_timeout")]
        #pragma warning disable CS1591
        Lock_timeout,
        #pragma warning restore CS1591
    }
}
