// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Distinguishes the authorized connect application object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuthorizedConnectApplicationList_data_object
    {
        [EnumMember(Value = "authorized_connect_application")]
        #pragma warning disable CS1591
        Authorized_connect_application,
        #pragma warning restore CS1591
    }
}
