// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The error code identifying the type of error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CannotDeleteLastCertificateCode
    {
        [EnumMember(Value = "cannot_delete_last_certificate")]
        #pragma warning disable CS1591
        CannotDeleteLastCertificate,
        #pragma warning restore CS1591
    }
}
