// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The error code identifying the type of error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ClaimDeniedCode
    {
        [EnumMember(Value = "claim_denied")]
        #pragma warning disable CS1591
        ClaimDenied,
        #pragma warning restore CS1591
    }
}
