// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConnectedAccountWriteResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A mutable, non-unique display name for the provider account connection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountDisplayName { get; set; }
#nullable restore
#else
        public string AccountDisplayName { get; set; }
#endif
        /// <summary>A best-effort identifier for the provider account this connection points at. It is correlation metadata, not the connection identifier or a selector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountIdentifier { get; set; }
#nullable restore
#else
        public string AccountIdentifier { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The last four characters of the API key, or `null` for OAuth connections.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKeyLast4 { get; set; }
#nullable restore
#else
        public string ApiKeyLast4 { get; set; }
#endif
        /// <summary>The authentication method used for this connection (`oauth`, `api_key`, or `client_credentials`). Defaults to `oauth` if absent.</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseAuthMethod? AuthMethod { get; set; }
        /// <summary>The client ID supplied for this connection. Only present when `auth_method` is `client_credentials`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>The last four characters of the client secret supplied for this connection, or `null` when it can&apos;t be read. Only present when `auth_method` is `client_credentials`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientSecretLast4 { get; set; }
#nullable restore
#else
        public string ClientSecretLast4 { get; set; }
#endif
        /// <summary>The connection-level configuration values stored for this connection — the fields the provider declares at `installation` scope, excluding secret and undeclared fields. Returned for every authentication method; empty when no stored values can be disclosed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseConfigProperty? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseConfigProperty Config { get; set; }
#endif
        /// <summary>Whether this row is the compatibility connection visible to undeclared clients or a standard peer for plural-aware clients. The role does not indicate preference or creation order.</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseConnectionRole? ConnectionRole { get; set; }
        /// <summary>The timestamp when the connection was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The unique identifier of the connected account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The connected account object.</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountObject? Object { get; set; }
        /// <summary>The [Organization](/reference/organization) identifier associated with this connection, or `null` if not scoped to an organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The OAuth scopes granted for this connection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Scopes { get; set; }
#nullable restore
#else
        public List<string> Scopes { get; set; }
#endif
        /// <summary>The state of the connected account:- `connected`: The connection is active and tokens are valid.- `needs_reauthorization`: The user needs to reauthorize the connection, typically because required scopes have changed.- `disconnected`: The connection has been disconnected.</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseState? State { get; set; }
        /// <summary>The timestamp when the connection was last updated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The [User](/reference/authkit/user) identifier associated with this connection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>Non-blocking warnings about an explicitly supplied label, omitted when no duplicate exists. Reads do not include this field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseWarningsItem>? Warnings { get; set; }
#nullable restore
#else
        public List<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseWarningsItem> Warnings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponse"/> and sets the default values.
        /// </summary>
        public ConnectedAccountWriteResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_display_name", n => { AccountDisplayName = n.GetStringValue(); } },
                { "account_identifier", n => { AccountIdentifier = n.GetStringValue(); } },
                { "api_key_last_4", n => { ApiKeyLast4 = n.GetStringValue(); } },
                { "auth_method", n => { AuthMethod = n.GetEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseAuthMethod>(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "client_secret_last_4", n => { ClientSecretLast4 = n.GetStringValue(); } },
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseConfigProperty>(global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseConfigProperty.CreateFromDiscriminatorValue); } },
                { "connection_role", n => { ConnectionRole = n.GetEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseConnectionRole>(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountObject>(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "scopes", n => { Scopes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseState>(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
                { "warnings", n => { Warnings = n.GetCollectionOfObjectValues<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseWarningsItem>(global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseWarningsItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_display_name", AccountDisplayName);
            writer.WriteStringValue("account_identifier", AccountIdentifier);
            writer.WriteStringValue("api_key_last_4", ApiKeyLast4);
            writer.WriteEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseAuthMethod>("auth_method", AuthMethod);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteStringValue("client_secret_last_4", ClientSecretLast4);
            writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseConfigProperty>("config", Config);
            writer.WriteEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseConnectionRole>("connection_role", ConnectionRole);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountObject>("object", Object);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteCollectionOfPrimitiveValues<string>("scopes", Scopes);
            writer.WriteEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseState>("state", State);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.WorkOs.OpenApiClient.Models.ConnectedAccountWriteResponseWarningsItem>("warnings", Warnings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
