// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateWebhookEndpointDto_events
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "authentication.email_verification_succeeded")]
        #pragma warning disable CS1591
        AuthenticationEmail_verification_succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.magic_auth_failed")]
        #pragma warning disable CS1591
        AuthenticationMagic_auth_failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.magic_auth_succeeded")]
        #pragma warning disable CS1591
        AuthenticationMagic_auth_succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.mfa_succeeded")]
        #pragma warning disable CS1591
        AuthenticationMfa_succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.oauth_failed")]
        #pragma warning disable CS1591
        AuthenticationOauth_failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.oauth_succeeded")]
        #pragma warning disable CS1591
        AuthenticationOauth_succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.password_failed")]
        #pragma warning disable CS1591
        AuthenticationPassword_failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.password_succeeded")]
        #pragma warning disable CS1591
        AuthenticationPassword_succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.passkey_failed")]
        #pragma warning disable CS1591
        AuthenticationPasskey_failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.passkey_succeeded")]
        #pragma warning disable CS1591
        AuthenticationPasskey_succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.sso_failed")]
        #pragma warning disable CS1591
        AuthenticationSso_failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.sso_started")]
        #pragma warning disable CS1591
        AuthenticationSso_started,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.sso_succeeded")]
        #pragma warning disable CS1591
        AuthenticationSso_succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.sso_timed_out")]
        #pragma warning disable CS1591
        AuthenticationSso_timed_out,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.radar_risk_detected")]
        #pragma warning disable CS1591
        AuthenticationRadar_risk_detected,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key.created")]
        #pragma warning disable CS1591
        Api_keyCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key.revoked")]
        #pragma warning disable CS1591
        Api_keyRevoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection.activated")]
        #pragma warning disable CS1591
        ConnectionActivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection.deactivated")]
        #pragma warning disable CS1591
        ConnectionDeactivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection.saml_certificate_renewal_required")]
        #pragma warning disable CS1591
        ConnectionSaml_certificate_renewal_required,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection.saml_certificate_renewed")]
        #pragma warning disable CS1591
        ConnectionSaml_certificate_renewed,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection.deleted")]
        #pragma warning disable CS1591
        ConnectionDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.activated")]
        #pragma warning disable CS1591
        DsyncActivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.deleted")]
        #pragma warning disable CS1591
        DsyncDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.group.created")]
        #pragma warning disable CS1591
        DsyncGroupCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.group.deleted")]
        #pragma warning disable CS1591
        DsyncGroupDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.group.updated")]
        #pragma warning disable CS1591
        DsyncGroupUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.group.user_added")]
        #pragma warning disable CS1591
        DsyncGroupUser_added,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.group.user_removed")]
        #pragma warning disable CS1591
        DsyncGroupUser_removed,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.user.created")]
        #pragma warning disable CS1591
        DsyncUserCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.user.deleted")]
        #pragma warning disable CS1591
        DsyncUserDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.user.updated")]
        #pragma warning disable CS1591
        DsyncUserUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_verification.created")]
        #pragma warning disable CS1591
        Email_verificationCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "group.created")]
        #pragma warning disable CS1591
        GroupCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "group.deleted")]
        #pragma warning disable CS1591
        GroupDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "group.member_added")]
        #pragma warning disable CS1591
        GroupMember_added,
        #pragma warning restore CS1591
        [EnumMember(Value = "group.member_removed")]
        #pragma warning disable CS1591
        GroupMember_removed,
        #pragma warning restore CS1591
        [EnumMember(Value = "group.updated")]
        #pragma warning disable CS1591
        GroupUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "flag.created")]
        #pragma warning disable CS1591
        FlagCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "flag.deleted")]
        #pragma warning disable CS1591
        FlagDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "flag.updated")]
        #pragma warning disable CS1591
        FlagUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "flag.rule_updated")]
        #pragma warning disable CS1591
        FlagRule_updated,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitation.accepted")]
        #pragma warning disable CS1591
        InvitationAccepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitation.created")]
        #pragma warning disable CS1591
        InvitationCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitation.resent")]
        #pragma warning disable CS1591
        InvitationResent,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitation.revoked")]
        #pragma warning disable CS1591
        InvitationRevoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "magic_auth.created")]
        #pragma warning disable CS1591
        Magic_authCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization.created")]
        #pragma warning disable CS1591
        OrganizationCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization.deleted")]
        #pragma warning disable CS1591
        OrganizationDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization.updated")]
        #pragma warning disable CS1591
        OrganizationUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_domain.created")]
        #pragma warning disable CS1591
        Organization_domainCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_domain.deleted")]
        #pragma warning disable CS1591
        Organization_domainDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_domain.updated")]
        #pragma warning disable CS1591
        Organization_domainUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_domain.verified")]
        #pragma warning disable CS1591
        Organization_domainVerified,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_domain.verification_failed")]
        #pragma warning disable CS1591
        Organization_domainVerification_failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "password_reset.created")]
        #pragma warning disable CS1591
        Password_resetCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "password_reset.succeeded")]
        #pragma warning disable CS1591
        Password_resetSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "user.created")]
        #pragma warning disable CS1591
        UserCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "user.updated")]
        #pragma warning disable CS1591
        UserUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "user.deleted")]
        #pragma warning disable CS1591
        UserDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_membership.created")]
        #pragma warning disable CS1591
        Organization_membershipCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_membership.deleted")]
        #pragma warning disable CS1591
        Organization_membershipDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_membership.updated")]
        #pragma warning disable CS1591
        Organization_membershipUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "role.created")]
        #pragma warning disable CS1591
        RoleCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "role.deleted")]
        #pragma warning disable CS1591
        RoleDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "role.updated")]
        #pragma warning disable CS1591
        RoleUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_role.created")]
        #pragma warning disable CS1591
        Organization_roleCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_role.deleted")]
        #pragma warning disable CS1591
        Organization_roleDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_role.updated")]
        #pragma warning disable CS1591
        Organization_roleUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "permission.created")]
        #pragma warning disable CS1591
        PermissionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "permission.deleted")]
        #pragma warning disable CS1591
        PermissionDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "permission.updated")]
        #pragma warning disable CS1591
        PermissionUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "session.created")]
        #pragma warning disable CS1591
        SessionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "session.revoked")]
        #pragma warning disable CS1591
        SessionRevoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "waitlist_user.approved")]
        #pragma warning disable CS1591
        Waitlist_userApproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "waitlist_user.created")]
        #pragma warning disable CS1591
        Waitlist_userCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "waitlist_user.denied")]
        #pragma warning disable CS1591
        Waitlist_userDenied,
        #pragma warning restore CS1591
    }
}
