// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The type of application to create.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateM2MApplicationDto_application_type
    {
        [EnumMember(Value = "m2m")]
        #pragma warning disable CS1591
        M2M,
        #pragma warning restore CS1591
    }
}
