// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateWaitlistEntryDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Object containing additional key/value pairs collected with the waitlist entry. Values are user-provided — treat them as untrusted input when rendering or exporting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.CreateWaitlistEntryDtoAdditionalFieldsProperty? AdditionalFields { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.CreateWaitlistEntryDtoAdditionalFieldsProperty AdditionalFields { get; set; }
#endif
        /// <summary>The email address of the user joining the waitlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Whether to send the waitlist confirmation email to the user. Defaults to `false`. No email is sent when the waitlist confirmation email is disabled in the environment, even if `send_confirmation_email` is `true`.</summary>
        public bool? SendConfirmationEmail { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.CreateWaitlistEntryDto"/> and sets the default values.
        /// </summary>
        public CreateWaitlistEntryDto()
        {
            AdditionalData = new Dictionary<string, object>();
            SendConfirmationEmail = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.CreateWaitlistEntryDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.WorkOs.OpenApiClient.Models.CreateWaitlistEntryDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.WorkOs.OpenApiClient.Models.CreateWaitlistEntryDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additional_fields", n => { AdditionalFields = n.GetObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.CreateWaitlistEntryDtoAdditionalFieldsProperty>(global::Soenneker.WorkOs.OpenApiClient.Models.CreateWaitlistEntryDtoAdditionalFieldsProperty.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "send_confirmation_email", n => { SendConfirmationEmail = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.CreateWaitlistEntryDtoAdditionalFieldsProperty>("additional_fields", AdditionalFields);
            writer.WriteStringValue("email", Email);
            writer.WriteBoolValue("send_confirmation_email", SendConfirmationEmail);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
