// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateWebhookEndpointDtoEventsItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "agent.registration.created")]
        #pragma warning disable CS1591
        AgentRegistrationCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "agent.registration.claim.attempt.created")]
        #pragma warning disable CS1591
        AgentRegistrationClaimAttemptCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "agent.registration.claim.completed")]
        #pragma warning disable CS1591
        AgentRegistrationClaimCompleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "agent.registration.credential.issued")]
        #pragma warning disable CS1591
        AgentRegistrationCredentialIssued,
        #pragma warning restore CS1591
        [EnumMember(Value = "agent.registration.expired")]
        #pragma warning disable CS1591
        AgentRegistrationExpired,
        #pragma warning restore CS1591
        [EnumMember(Value = "agent.registration.organization.switched")]
        #pragma warning disable CS1591
        AgentRegistrationOrganizationSwitched,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.email_verification_succeeded")]
        #pragma warning disable CS1591
        AuthenticationEmailVerificationSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.magic_auth_failed")]
        #pragma warning disable CS1591
        AuthenticationMagicAuthFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.magic_auth_succeeded")]
        #pragma warning disable CS1591
        AuthenticationMagicAuthSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.mfa_succeeded")]
        #pragma warning disable CS1591
        AuthenticationMfaSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.oauth_failed")]
        #pragma warning disable CS1591
        AuthenticationOAuthFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.oauth_succeeded")]
        #pragma warning disable CS1591
        AuthenticationOAuthSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.password_failed")]
        #pragma warning disable CS1591
        AuthenticationPasswordFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.password_succeeded")]
        #pragma warning disable CS1591
        AuthenticationPasswordSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.passkey_failed")]
        #pragma warning disable CS1591
        AuthenticationPasskeyFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.passkey_succeeded")]
        #pragma warning disable CS1591
        AuthenticationPasskeySucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.sso_failed")]
        #pragma warning disable CS1591
        AuthenticationSsoFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.sso_started")]
        #pragma warning disable CS1591
        AuthenticationSsoStarted,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.sso_succeeded")]
        #pragma warning disable CS1591
        AuthenticationSsoSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.sso_timed_out")]
        #pragma warning disable CS1591
        AuthenticationSsoTimedOut,
        #pragma warning restore CS1591
        [EnumMember(Value = "radar.challenge_created")]
        #pragma warning disable CS1591
        RadarChallengeCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.radar_risk_detected")]
        #pragma warning disable CS1591
        AuthenticationRadarRiskDetected,
        #pragma warning restore CS1591
        [EnumMember(Value = "authentication.reauthentication_succeeded")]
        #pragma warning disable CS1591
        AuthenticationReauthenticationSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key.created")]
        #pragma warning disable CS1591
        ApiKeyCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key.revoked")]
        #pragma warning disable CS1591
        ApiKeyRevoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key.updated")]
        #pragma warning disable CS1591
        ApiKeyUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection.activated")]
        #pragma warning disable CS1591
        ConnectionActivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection.deactivated")]
        #pragma warning disable CS1591
        ConnectionDeactivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection.saml_certificate_renewal_required")]
        #pragma warning disable CS1591
        ConnectionSamlCertificateRenewalRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection.saml_certificate_renewed")]
        #pragma warning disable CS1591
        ConnectionSamlCertificateRenewed,
        #pragma warning restore CS1591
        [EnumMember(Value = "connection.deleted")]
        #pragma warning disable CS1591
        ConnectionDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.activated")]
        #pragma warning disable CS1591
        DsyncActivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.deleted")]
        #pragma warning disable CS1591
        DsyncDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.group.created")]
        #pragma warning disable CS1591
        DsyncGroupCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.group.deleted")]
        #pragma warning disable CS1591
        DsyncGroupDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.group.updated")]
        #pragma warning disable CS1591
        DsyncGroupUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.group.user_added")]
        #pragma warning disable CS1591
        DsyncGroupUserAdded,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.group.user_removed")]
        #pragma warning disable CS1591
        DsyncGroupUserRemoved,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.user.created")]
        #pragma warning disable CS1591
        DsyncUserCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.user.deleted")]
        #pragma warning disable CS1591
        DsyncUserDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "dsync.user.updated")]
        #pragma warning disable CS1591
        DsyncUserUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_verification.created")]
        #pragma warning disable CS1591
        EmailVerificationCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "group.created")]
        #pragma warning disable CS1591
        GroupCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "group.deleted")]
        #pragma warning disable CS1591
        GroupDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "group.member_added")]
        #pragma warning disable CS1591
        GroupMemberAdded,
        #pragma warning restore CS1591
        [EnumMember(Value = "group.member_removed")]
        #pragma warning disable CS1591
        GroupMemberRemoved,
        #pragma warning restore CS1591
        [EnumMember(Value = "group.updated")]
        #pragma warning disable CS1591
        GroupUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "flag.created")]
        #pragma warning disable CS1591
        FlagCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "flag.deleted")]
        #pragma warning disable CS1591
        FlagDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "flag.updated")]
        #pragma warning disable CS1591
        FlagUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "flag.rule_updated")]
        #pragma warning disable CS1591
        FlagRuleUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitation.accepted")]
        #pragma warning disable CS1591
        InvitationAccepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitation.created")]
        #pragma warning disable CS1591
        InvitationCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitation.resent")]
        #pragma warning disable CS1591
        InvitationResent,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitation.revoked")]
        #pragma warning disable CS1591
        InvitationRevoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "magic_auth.created")]
        #pragma warning disable CS1591
        MagicAuthCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization.created")]
        #pragma warning disable CS1591
        OrganizationCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization.deleted")]
        #pragma warning disable CS1591
        OrganizationDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization.updated")]
        #pragma warning disable CS1591
        OrganizationUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_domain.created")]
        #pragma warning disable CS1591
        OrganizationDomainCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_domain.deleted")]
        #pragma warning disable CS1591
        OrganizationDomainDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_domain.updated")]
        #pragma warning disable CS1591
        OrganizationDomainUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_domain.verified")]
        #pragma warning disable CS1591
        OrganizationDomainVerified,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_domain.verification_failed")]
        #pragma warning disable CS1591
        OrganizationDomainVerificationFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "password_reset.created")]
        #pragma warning disable CS1591
        PasswordResetCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "password_reset.succeeded")]
        #pragma warning disable CS1591
        PasswordResetSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "user.created")]
        #pragma warning disable CS1591
        UserCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "user.updated")]
        #pragma warning disable CS1591
        UserUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "user.deleted")]
        #pragma warning disable CS1591
        UserDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_membership.created")]
        #pragma warning disable CS1591
        OrganizationMembershipCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_membership.deleted")]
        #pragma warning disable CS1591
        OrganizationMembershipDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_membership.updated")]
        #pragma warning disable CS1591
        OrganizationMembershipUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "role.created")]
        #pragma warning disable CS1591
        RoleCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "role.deleted")]
        #pragma warning disable CS1591
        RoleDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "role.updated")]
        #pragma warning disable CS1591
        RoleUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_role.created")]
        #pragma warning disable CS1591
        OrganizationRoleCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_role.deleted")]
        #pragma warning disable CS1591
        OrganizationRoleDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization_role.updated")]
        #pragma warning disable CS1591
        OrganizationRoleUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "permission.created")]
        #pragma warning disable CS1591
        PermissionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "permission.deleted")]
        #pragma warning disable CS1591
        PermissionDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "permission.updated")]
        #pragma warning disable CS1591
        PermissionUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "pipes.connected_account.connected")]
        #pragma warning disable CS1591
        PipesConnectedAccountConnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "pipes.connected_account.connection_failed")]
        #pragma warning disable CS1591
        PipesConnectedAccountConnectionFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "pipes.connected_account.disconnected")]
        #pragma warning disable CS1591
        PipesConnectedAccountDisconnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "pipes.connected_account.reauthorization_needed")]
        #pragma warning disable CS1591
        PipesConnectedAccountReauthorizationNeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "session.created")]
        #pragma warning disable CS1591
        SessionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "session.revoked")]
        #pragma warning disable CS1591
        SessionRevoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "waitlist_user.approved")]
        #pragma warning disable CS1591
        WaitlistUserApproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "waitlist_user.created")]
        #pragma warning disable CS1591
        WaitlistUserCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "waitlist_user.denied")]
        #pragma warning disable CS1591
        WaitlistUserDenied,
        #pragma warning restore CS1591
    }
}
