// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>How client credentials are sent when exchanging authorization codes and refreshing tokens.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomProviderDefinitionDtoAuthenticateVia
    {
        [EnumMember(Value = "request_body")]
        #pragma warning disable CS1591
        RequestBody,
        #pragma warning restore CS1591
        [EnumMember(Value = "basic_auth_header")]
        #pragma warning disable CS1591
        BasicAuthHeader,
        #pragma warning restore CS1591
    }
}
