// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Indicates credentials are not available.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DataIntegrationCredentialsResponseOneOf3_active
    {
        [EnumMember(Value = "False")]
        #pragma warning disable CS1591
        FalseValue,
        #pragma warning restore CS1591
    }
}
