// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Indicates whether the access token is valid and ready for use, or if reauthorization is required.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DataIntegrationAccessTokenResponseOneOf1_active
    {
        [EnumMember(Value = "True")]
        #pragma warning disable CS1591
        TrueValue,
        #pragma warning restore CS1591
    }
}
