// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Distinguishes the Directory object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Directory_object
    {
        [EnumMember(Value = "directory")]
        #pragma warning disable CS1591
        Directory,
        #pragma warning restore CS1591
    }
}
