// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Distinguishes the Directory Group object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DirectoryGroup_object
    {
        [EnumMember(Value = "directory_group")]
        #pragma warning disable CS1591
        DirectoryGroup,
        #pragma warning restore CS1591
    }
}
