// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The error code identifying the type of error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EmailChangeNotNeededCode
    {
        [EnumMember(Value = "email_change_not_needed")]
        #pragma warning disable CS1591
        EmailChangeNotNeeded,
        #pragma warning restore CS1591
    }
}
