// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The error code identifying the type of error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExternalAuthSessionAlreadyCompletedCode
    {
        [EnumMember(Value = "external_auth_session_already_completed")]
        #pragma warning disable CS1591
        ExternalAuthSessionAlreadyCompleted,
        #pragma warning restore CS1591
    }
}
