// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Distinguishes the group role assignment object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GroupRoleAssignment_object
    {
        [EnumMember(Value = "group_role_assignment")]
        #pragma warning disable CS1591
        GroupRoleAssignment,
        #pragma warning restore CS1591
    }
}
