// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The Group object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Group_object
    {
        [EnumMember(Value = "group")]
        #pragma warning disable CS1591
        Group,
        #pragma warning restore CS1591
    }
}
