// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InvalidClientError
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "invalid_client")]
        #pragma warning disable CS1591
        InvalidClient,
        #pragma warning restore CS1591
    }
}
