// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InviteItContactDtoIntentsItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "sso")]
        #pragma warning disable CS1591
        Sso,
        #pragma warning restore CS1591
        [EnumMember(Value = "directory_sync")]
        #pragma warning disable CS1591
        DirectorySync,
        #pragma warning restore CS1591
        [EnumMember(Value = "log_streams")]
        #pragma warning disable CS1591
        LogStreams,
        #pragma warning restore CS1591
        [EnumMember(Value = "domain_verification")]
        #pragma warning disable CS1591
        DomainVerification,
        #pragma warning restore CS1591
        [EnumMember(Value = "bring_your_own_key")]
        #pragma warning disable CS1591
        BringYourOwnKey,
        #pragma warning restore CS1591
    }
}
