// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Key use (signature).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum JwksResponseKeysItem_use
    {
        [EnumMember(Value = "sig")]
        #pragma warning disable CS1591
        Sig,
        #pragma warning restore CS1591
    }
}
