// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Distinguishes the Magic Auth object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MagicAuth_object
    {
        [EnumMember(Value = "magic_auth")]
        #pragma warning disable CS1591
        Magic_auth,
        #pragma warning restore CS1591
    }
}
