// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Distinguishes the connect application secret object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NewConnectApplicationSecret_object
    {
        [EnumMember(Value = "connect_application_secret")]
        #pragma warning disable CS1591
        Connect_application_secret,
        #pragma warning restore CS1591
    }
}
