// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The type of application to create.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OAuthApplicationType
    {
        [EnumMember(Value = "oauth")]
        #pragma warning disable CS1591
        OAuth,
        #pragma warning restore CS1591
    }
}
