// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The error code identifying the type of error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PasswordStrengthErrorCode
    {
        [EnumMember(Value = "password_strength_error")]
        #pragma warning disable CS1591
        PasswordStrengthError,
        #pragma warning restore CS1591
    }
}
