// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The type of SSO connection.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Profile_connection_type
    {
        [EnumMember(Value = "Pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADFSSAML")]
        #pragma warning disable CS1591
        ADFSSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdpOidc")]
        #pragma warning disable CS1591
        AdpOidc,
        #pragma warning restore CS1591
        [EnumMember(Value = "AppleOAuth")]
        #pragma warning disable CS1591
        AppleOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "Auth0Migration")]
        #pragma warning disable CS1591
        Auth0Migration,
        #pragma warning restore CS1591
        [EnumMember(Value = "Auth0SAML")]
        #pragma warning disable CS1591
        Auth0SAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "AzureSAML")]
        #pragma warning disable CS1591
        AzureSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "BitbucketOAuth")]
        #pragma warning disable CS1591
        BitbucketOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "CasSAML")]
        #pragma warning disable CS1591
        CasSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "ClassLinkSAML")]
        #pragma warning disable CS1591
        ClassLinkSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "CleverOIDC")]
        #pragma warning disable CS1591
        CleverOIDC,
        #pragma warning restore CS1591
        [EnumMember(Value = "CloudflareSAML")]
        #pragma warning disable CS1591
        CloudflareSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "CyberArkSAML")]
        #pragma warning disable CS1591
        CyberArkSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "DiscordOAuth")]
        #pragma warning disable CS1591
        DiscordOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "DuoSAML")]
        #pragma warning disable CS1591
        DuoSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "EntraIdOIDC")]
        #pragma warning disable CS1591
        EntraIdOIDC,
        #pragma warning restore CS1591
        [EnumMember(Value = "GenericOIDC")]
        #pragma warning disable CS1591
        GenericOIDC,
        #pragma warning restore CS1591
        [EnumMember(Value = "GenericSAML")]
        #pragma warning disable CS1591
        GenericSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "GitHubOAuth")]
        #pragma warning disable CS1591
        GitHubOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "GitLabOAuth")]
        #pragma warning disable CS1591
        GitLabOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "GoogleOAuth")]
        #pragma warning disable CS1591
        GoogleOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "GoogleOIDC")]
        #pragma warning disable CS1591
        GoogleOIDC,
        #pragma warning restore CS1591
        [EnumMember(Value = "GoogleSAML")]
        #pragma warning disable CS1591
        GoogleSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "IntuitOAuth")]
        #pragma warning disable CS1591
        IntuitOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "JumpCloudSAML")]
        #pragma warning disable CS1591
        JumpCloudSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "KeycloakSAML")]
        #pragma warning disable CS1591
        KeycloakSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "LastPassSAML")]
        #pragma warning disable CS1591
        LastPassSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "LinkedInOAuth")]
        #pragma warning disable CS1591
        LinkedInOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "LoginGovOidc")]
        #pragma warning disable CS1591
        LoginGovOidc,
        #pragma warning restore CS1591
        [EnumMember(Value = "MagicLink")]
        #pragma warning disable CS1591
        MagicLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "MicrosoftOAuth")]
        #pragma warning disable CS1591
        MicrosoftOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "MiniOrangeSAML")]
        #pragma warning disable CS1591
        MiniOrangeSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "NetIqSAML")]
        #pragma warning disable CS1591
        NetIqSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "OktaOIDC")]
        #pragma warning disable CS1591
        OktaOIDC,
        #pragma warning restore CS1591
        [EnumMember(Value = "OktaSAML")]
        #pragma warning disable CS1591
        OktaSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "OneLoginSAML")]
        #pragma warning disable CS1591
        OneLoginSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "OracleSAML")]
        #pragma warning disable CS1591
        OracleSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "PingFederateSAML")]
        #pragma warning disable CS1591
        PingFederateSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "PingOneSAML")]
        #pragma warning disable CS1591
        PingOneSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "RipplingSAML")]
        #pragma warning disable CS1591
        RipplingSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesforceSAML")]
        #pragma warning disable CS1591
        SalesforceSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "ShibbolethGenericSAML")]
        #pragma warning disable CS1591
        ShibbolethGenericSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "ShibbolethSAML")]
        #pragma warning disable CS1591
        ShibbolethSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "SimpleSamlPhpSAML")]
        #pragma warning disable CS1591
        SimpleSamlPhpSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesforceOAuth")]
        #pragma warning disable CS1591
        SalesforceOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "SlackOAuth")]
        #pragma warning disable CS1591
        SlackOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "TestIdp")]
        #pragma warning disable CS1591
        TestIdp,
        #pragma warning restore CS1591
        [EnumMember(Value = "VercelMarketplaceOAuth")]
        #pragma warning disable CS1591
        VercelMarketplaceOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "VercelOAuth")]
        #pragma warning disable CS1591
        VercelOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "VMwareSAML")]
        #pragma warning disable CS1591
        VMwareSAML,
        #pragma warning restore CS1591
        [EnumMember(Value = "XeroOAuth")]
        #pragma warning disable CS1591
        XeroOAuth,
        #pragma warning restore CS1591
    }
}
