// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.ProfileRoleMember1"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.SlimRole"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProfileRole : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.ProfileRoleMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.ProfileRoleMember1? ProfileRoleMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.ProfileRoleMember1 ProfileRoleMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.SlimRole"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.SlimRole? SlimRole { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.SlimRole SlimRole { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.ProfileRole"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.WorkOs.OpenApiClient.Models.ProfileRole CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.WorkOs.OpenApiClient.Models.ProfileRole();
            if("SlimRole".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SlimRole = new global::Soenneker.WorkOs.OpenApiClient.Models.SlimRole();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ProfileRoleMember1 != null)
            {
                return ProfileRoleMember1.GetFieldDeserializers();
            }
            else if(SlimRole != null)
            {
                return SlimRole.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ProfileRoleMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.ProfileRoleMember1>(null, ProfileRoleMember1);
            }
            else if(SlimRole != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.SlimRole>(null, SlimRole);
            }
        }
    }
}
#pragma warning restore CS0618
