// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The action being performed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RadarStandaloneControllerAssess_action
    {
        [EnumMember(Value = "sign-up")]
        #pragma warning disable CS1591
        SignUp,
        #pragma warning restore CS1591
        [EnumMember(Value = "sign-in")]
        #pragma warning disable CS1591
        SignIn,
        #pragma warning restore CS1591
    }
}
