// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The error code identifying the type of error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SpSigningCertAlreadyExistsCode
    {
        [EnumMember(Value = "sp_signing_cert_already_exists")]
        #pragma warning disable CS1591
        SpSigningCertAlreadyExists,
        #pragma warning restore CS1591
    }
}
