// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SsoTokenResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>An access token that can be exchanged for a user profile. Access tokens are short-lived — see the `expires_in` field for the exact lifetime.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessToken { get; set; }
#nullable restore
#else
        public string AccessToken { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The lifetime of the access token in seconds.</summary>
        public int? ExpiresIn { get; set; }
        /// <summary>OAuth tokens issued by the identity provider, if available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.SsoTokenResponse_oauth_tokens? OauthTokens { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.SsoTokenResponse_oauth_tokens OauthTokens { get; set; }
#endif
        /// <summary>The user profile returned by the identity provider.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.Profile? Profile { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.Profile Profile { get; set; }
#endif
        /// <summary>The type of token issued.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenType { get; set; }
#nullable restore
#else
        public string TokenType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.SsoTokenResponse"/> and sets the default values.
        /// </summary>
        public SsoTokenResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.SsoTokenResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.WorkOs.OpenApiClient.Models.SsoTokenResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.WorkOs.OpenApiClient.Models.SsoTokenResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_token", n => { AccessToken = n.GetStringValue(); } },
                { "expires_in", n => { ExpiresIn = n.GetIntValue(); } },
                { "oauth_tokens", n => { OauthTokens = n.GetObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.SsoTokenResponse_oauth_tokens>(global::Soenneker.WorkOs.OpenApiClient.Models.SsoTokenResponse_oauth_tokens.CreateFromDiscriminatorValue); } },
                { "profile", n => { Profile = n.GetObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.Profile>(global::Soenneker.WorkOs.OpenApiClient.Models.Profile.CreateFromDiscriminatorValue); } },
                { "token_type", n => { TokenType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("access_token", AccessToken);
            writer.WriteIntValue("expires_in", ExpiresIn);
            writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.SsoTokenResponse_oauth_tokens>("oauth_tokens", OauthTokens);
            writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.Profile>("profile", Profile);
            writer.WriteStringValue("token_type", TokenType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
