// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The period Audit Log events will be retained. Valid values are `1_MONTH` through `11_MONTHS` in one-month increments and `1_YEAR` through `10_YEARS` in one-year increments. Mutually exclusive with `retention_period_in_days`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateAuditLogsRetentionDtoOneOf1RetentionPeriod
    {
        [EnumMember(Value = "1_MONTH")]
        #pragma warning disable CS1591
        Value1Month,
        #pragma warning restore CS1591
        [EnumMember(Value = "2_MONTHS")]
        #pragma warning disable CS1591
        Value2Months,
        #pragma warning restore CS1591
        [EnumMember(Value = "3_MONTHS")]
        #pragma warning disable CS1591
        Value3Months,
        #pragma warning restore CS1591
        [EnumMember(Value = "4_MONTHS")]
        #pragma warning disable CS1591
        Value4Months,
        #pragma warning restore CS1591
        [EnumMember(Value = "5_MONTHS")]
        #pragma warning disable CS1591
        Value5Months,
        #pragma warning restore CS1591
        [EnumMember(Value = "6_MONTHS")]
        #pragma warning disable CS1591
        Value6Months,
        #pragma warning restore CS1591
        [EnumMember(Value = "7_MONTHS")]
        #pragma warning disable CS1591
        Value7Months,
        #pragma warning restore CS1591
        [EnumMember(Value = "8_MONTHS")]
        #pragma warning disable CS1591
        Value8Months,
        #pragma warning restore CS1591
        [EnumMember(Value = "9_MONTHS")]
        #pragma warning disable CS1591
        Value9Months,
        #pragma warning restore CS1591
        [EnumMember(Value = "10_MONTHS")]
        #pragma warning disable CS1591
        Value10Months,
        #pragma warning restore CS1591
        [EnumMember(Value = "11_MONTHS")]
        #pragma warning disable CS1591
        Value11Months,
        #pragma warning restore CS1591
        [EnumMember(Value = "1_YEAR")]
        #pragma warning disable CS1591
        Value1Year,
        #pragma warning restore CS1591
        [EnumMember(Value = "2_YEARS")]
        #pragma warning disable CS1591
        Value2Years,
        #pragma warning restore CS1591
        [EnumMember(Value = "3_YEARS")]
        #pragma warning disable CS1591
        Value3Years,
        #pragma warning restore CS1591
        [EnumMember(Value = "4_YEARS")]
        #pragma warning disable CS1591
        Value4Years,
        #pragma warning restore CS1591
        [EnumMember(Value = "5_YEARS")]
        #pragma warning disable CS1591
        Value5Years,
        #pragma warning restore CS1591
        [EnumMember(Value = "6_YEARS")]
        #pragma warning disable CS1591
        Value6Years,
        #pragma warning restore CS1591
        [EnumMember(Value = "7_YEARS")]
        #pragma warning disable CS1591
        Value7Years,
        #pragma warning restore CS1591
        [EnumMember(Value = "8_YEARS")]
        #pragma warning disable CS1591
        Value8Years,
        #pragma warning restore CS1591
        [EnumMember(Value = "9_YEARS")]
        #pragma warning disable CS1591
        Value9Years,
        #pragma warning restore CS1591
        [EnumMember(Value = "10_YEARS")]
        #pragma warning disable CS1591
        Value10Years,
        #pragma warning restore CS1591
    }
}
