// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember1"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember2"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember3"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateUserlandUserOrganizationMembershipDto : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember1? UpdateUserlandUserOrganizationMembershipDtoMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember1 UpdateUserlandUserOrganizationMembershipDtoMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember2? UpdateUserlandUserOrganizationMembershipDtoMember2 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember2 UpdateUserlandUserOrganizationMembershipDtoMember2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember3? UpdateUserlandUserOrganizationMembershipDtoMember3 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember3 UpdateUserlandUserOrganizationMembershipDtoMember3 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDto();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateUserlandUserOrganizationMembershipDtoMember1 = new global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember1();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateUserlandUserOrganizationMembershipDtoMember2 = new global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember2();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateUserlandUserOrganizationMembershipDtoMember3 = new global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember3();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(UpdateUserlandUserOrganizationMembershipDtoMember1 != null)
            {
                return UpdateUserlandUserOrganizationMembershipDtoMember1.GetFieldDeserializers();
            }
            else if(UpdateUserlandUserOrganizationMembershipDtoMember2 != null)
            {
                return UpdateUserlandUserOrganizationMembershipDtoMember2.GetFieldDeserializers();
            }
            else if(UpdateUserlandUserOrganizationMembershipDtoMember3 != null)
            {
                return UpdateUserlandUserOrganizationMembershipDtoMember3.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(UpdateUserlandUserOrganizationMembershipDtoMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember1>(null, UpdateUserlandUserOrganizationMembershipDtoMember1);
            }
            else if(UpdateUserlandUserOrganizationMembershipDtoMember2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember2>(null, UpdateUserlandUserOrganizationMembershipDtoMember2);
            }
            else if(UpdateUserlandUserOrganizationMembershipDtoMember3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UpdateUserlandUserOrganizationMembershipDtoMember3>(null, UpdateUserlandUserOrganizationMembershipDtoMember3);
            }
        }
    }
}
#pragma warning restore CS0618
