// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserlandSessionsControllerAuthenticate0Member1_grant_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "authorization_code")]
        #pragma warning disable CS1591
        Authorization_code,
        #pragma warning restore CS1591
    }
}
