// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserlandAuthenticateResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A JWT containing information about the current session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessToken { get; set; }
#nullable restore
#else
        public string AccessToken { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The authentication method used to initiate the session.</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_authentication_method? AuthenticationMethod { get; set; }
        /// <summary>An authorization code that can be exchanged for tokens by a different application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthkitAuthorizationCode { get; set; }
#nullable restore
#else
        public string AuthkitAuthorizationCode { get; set; }
#endif
        /// <summary>Information about the impersonator if this session was created via impersonation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_impersonator? Impersonator { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_impersonator Impersonator { get; set; }
#endif
        /// <summary>The OAuth tokens from the identity provider, if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_oauth_tokens? OauthTokens { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_oauth_tokens OauthTokens { get; set; }
#endif
        /// <summary>The ID of the organization the user selected to sign in to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>[Exchange this token](/reference/authkit/authentication/refresh-token) for a new access token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefreshToken { get; set; }
#nullable restore
#else
        public string RefreshToken { get; set; }
#endif
        /// <summary>The corresponding [user](/reference/authkit/user) object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandUser? User { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandUser User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse"/> and sets the default values.
        /// </summary>
        public UserlandAuthenticateResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_token", n => { AccessToken = n.GetStringValue(); } },
                { "authentication_method", n => { AuthenticationMethod = n.GetEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_authentication_method>(); } },
                { "authkit_authorization_code", n => { AuthkitAuthorizationCode = n.GetStringValue(); } },
                { "impersonator", n => { Impersonator = n.GetObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_impersonator>(global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_impersonator.CreateFromDiscriminatorValue); } },
                { "oauth_tokens", n => { OauthTokens = n.GetObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_oauth_tokens>(global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_oauth_tokens.CreateFromDiscriminatorValue); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "refresh_token", n => { RefreshToken = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandUser>(global::Soenneker.WorkOs.OpenApiClient.Models.UserlandUser.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("access_token", AccessToken);
            writer.WriteEnumValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_authentication_method>("authentication_method", AuthenticationMethod);
            writer.WriteStringValue("authkit_authorization_code", AuthkitAuthorizationCode);
            writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_impersonator>("impersonator", Impersonator);
            writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandAuthenticateResponse_oauth_tokens>("oauth_tokens", OauthTokens);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteStringValue("refresh_token", RefreshToken);
            writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandUser>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
