// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf1"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf10"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf2"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf3"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf4"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf5"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf6"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf7"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf8"/>, <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf9"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserlandSessionsControllerAuthenticate0Request : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf1? UserlandSessionsControllerAuthenticate0RequestOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf1 UserlandSessionsControllerAuthenticate0RequestOneOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf10? UserlandSessionsControllerAuthenticate0RequestOneOf10 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf10 UserlandSessionsControllerAuthenticate0RequestOneOf10 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf2? UserlandSessionsControllerAuthenticate0RequestOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf2 UserlandSessionsControllerAuthenticate0RequestOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf3? UserlandSessionsControllerAuthenticate0RequestOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf3 UserlandSessionsControllerAuthenticate0RequestOneOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf4? UserlandSessionsControllerAuthenticate0RequestOneOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf4 UserlandSessionsControllerAuthenticate0RequestOneOf4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf5? UserlandSessionsControllerAuthenticate0RequestOneOf5 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf5 UserlandSessionsControllerAuthenticate0RequestOneOf5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf6? UserlandSessionsControllerAuthenticate0RequestOneOf6 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf6 UserlandSessionsControllerAuthenticate0RequestOneOf6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf7? UserlandSessionsControllerAuthenticate0RequestOneOf7 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf7 UserlandSessionsControllerAuthenticate0RequestOneOf7 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf8? UserlandSessionsControllerAuthenticate0RequestOneOf8 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf8 UserlandSessionsControllerAuthenticate0RequestOneOf8 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf9? UserlandSessionsControllerAuthenticate0RequestOneOf9 { get; set; }
#nullable restore
#else
        public global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf9 UserlandSessionsControllerAuthenticate0RequestOneOf9 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0Request"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0Request CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0Request();
            if("UserlandSessionsControllerAuthenticate0RequestOneOf1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserlandSessionsControllerAuthenticate0RequestOneOf1 = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf1();
            }
            else if("UserlandSessionsControllerAuthenticate0RequestOneOf10".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserlandSessionsControllerAuthenticate0RequestOneOf10 = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf10();
            }
            else if("UserlandSessionsControllerAuthenticate0RequestOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserlandSessionsControllerAuthenticate0RequestOneOf2 = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf2();
            }
            else if("UserlandSessionsControllerAuthenticate0RequestOneOf3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserlandSessionsControllerAuthenticate0RequestOneOf3 = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf3();
            }
            else if("UserlandSessionsControllerAuthenticate0RequestOneOf4".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserlandSessionsControllerAuthenticate0RequestOneOf4 = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf4();
            }
            else if("UserlandSessionsControllerAuthenticate0RequestOneOf5".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserlandSessionsControllerAuthenticate0RequestOneOf5 = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf5();
            }
            else if("UserlandSessionsControllerAuthenticate0RequestOneOf6".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserlandSessionsControllerAuthenticate0RequestOneOf6 = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf6();
            }
            else if("UserlandSessionsControllerAuthenticate0RequestOneOf7".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserlandSessionsControllerAuthenticate0RequestOneOf7 = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf7();
            }
            else if("UserlandSessionsControllerAuthenticate0RequestOneOf8".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserlandSessionsControllerAuthenticate0RequestOneOf8 = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf8();
            }
            else if("UserlandSessionsControllerAuthenticate0RequestOneOf9".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserlandSessionsControllerAuthenticate0RequestOneOf9 = new global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf9();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(UserlandSessionsControllerAuthenticate0RequestOneOf1 != null)
            {
                return UserlandSessionsControllerAuthenticate0RequestOneOf1.GetFieldDeserializers();
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf10 != null)
            {
                return UserlandSessionsControllerAuthenticate0RequestOneOf10.GetFieldDeserializers();
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf2 != null)
            {
                return UserlandSessionsControllerAuthenticate0RequestOneOf2.GetFieldDeserializers();
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf3 != null)
            {
                return UserlandSessionsControllerAuthenticate0RequestOneOf3.GetFieldDeserializers();
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf4 != null)
            {
                return UserlandSessionsControllerAuthenticate0RequestOneOf4.GetFieldDeserializers();
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf5 != null)
            {
                return UserlandSessionsControllerAuthenticate0RequestOneOf5.GetFieldDeserializers();
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf6 != null)
            {
                return UserlandSessionsControllerAuthenticate0RequestOneOf6.GetFieldDeserializers();
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf7 != null)
            {
                return UserlandSessionsControllerAuthenticate0RequestOneOf7.GetFieldDeserializers();
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf8 != null)
            {
                return UserlandSessionsControllerAuthenticate0RequestOneOf8.GetFieldDeserializers();
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf9 != null)
            {
                return UserlandSessionsControllerAuthenticate0RequestOneOf9.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(UserlandSessionsControllerAuthenticate0RequestOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf1>(null, UserlandSessionsControllerAuthenticate0RequestOneOf1);
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf10 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf10>(null, UserlandSessionsControllerAuthenticate0RequestOneOf10);
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf2>(null, UserlandSessionsControllerAuthenticate0RequestOneOf2);
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf3>(null, UserlandSessionsControllerAuthenticate0RequestOneOf3);
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf4>(null, UserlandSessionsControllerAuthenticate0RequestOneOf4);
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf5>(null, UserlandSessionsControllerAuthenticate0RequestOneOf5);
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf6 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf6>(null, UserlandSessionsControllerAuthenticate0RequestOneOf6);
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf7 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf7>(null, UserlandSessionsControllerAuthenticate0RequestOneOf7);
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf8 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf8>(null, UserlandSessionsControllerAuthenticate0RequestOneOf8);
            }
            else if(UserlandSessionsControllerAuthenticate0RequestOneOf9 != null)
            {
                writer.WriteObjectValue<global::Soenneker.WorkOs.OpenApiClient.Models.UserlandSessionsControllerAuthenticate0RequestOneOf9>(null, UserlandSessionsControllerAuthenticate0RequestOneOf9);
            }
        }
    }
}
#pragma warning restore CS0618
