// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Whether the role was assigned directly or derived from a group.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserRoleAssignmentSourceType
    {
        [EnumMember(Value = "direct")]
        #pragma warning disable CS1591
        Direct,
        #pragma warning restore CS1591
        [EnumMember(Value = "group")]
        #pragma warning disable CS1591
        Group,
        #pragma warning restore CS1591
    }
}
