// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserlandSessionsControllerAuthenticate0Member6_grant_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "urn:workos:oauth:grant-type:mfa-totp")]
        #pragma warning disable CS1591
        UrnWorkosOauthGrantTypeMfaTotp,
        #pragma warning restore CS1591
    }
}
