// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserlandSsoControllerAuthorizeScreenHintParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "sign-up")]
        #pragma warning disable CS1591
        SignUp,
        #pragma warning restore CS1591
        [EnumMember(Value = "sign-in")]
        #pragma warning disable CS1591
        SignIn,
        #pragma warning restore CS1591
    }
}
