// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The authentication method used to initiate the session.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserlandAuthenticateResponse_authentication_method
    {
        [EnumMember(Value = "SSO")]
        #pragma warning disable CS1591
        SSO,
        #pragma warning restore CS1591
        [EnumMember(Value = "Password")]
        #pragma warning disable CS1591
        Password,
        #pragma warning restore CS1591
        [EnumMember(Value = "Passkey")]
        #pragma warning disable CS1591
        Passkey,
        #pragma warning restore CS1591
        [EnumMember(Value = "AppleOAuth")]
        #pragma warning disable CS1591
        AppleOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "BitbucketOAuth")]
        #pragma warning disable CS1591
        BitbucketOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "CrossAppAuth")]
        #pragma warning disable CS1591
        CrossAppAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "DiscordOAuth")]
        #pragma warning disable CS1591
        DiscordOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "ExternalAuth")]
        #pragma warning disable CS1591
        ExternalAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "GitHubOAuth")]
        #pragma warning disable CS1591
        GitHubOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "GitLabOAuth")]
        #pragma warning disable CS1591
        GitLabOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "GoogleOAuth")]
        #pragma warning disable CS1591
        GoogleOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "IntuitOAuth")]
        #pragma warning disable CS1591
        IntuitOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "LinkedInOAuth")]
        #pragma warning disable CS1591
        LinkedInOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "MicrosoftOAuth")]
        #pragma warning disable CS1591
        MicrosoftOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "SalesforceOAuth")]
        #pragma warning disable CS1591
        SalesforceOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "SlackOAuth")]
        #pragma warning disable CS1591
        SlackOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "VercelMarketplaceOAuth")]
        #pragma warning disable CS1591
        VercelMarketplaceOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "VercelOAuth")]
        #pragma warning disable CS1591
        VercelOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "XeroOAuth")]
        #pragma warning disable CS1591
        XeroOAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "MagicAuth")]
        #pragma warning disable CS1591
        MagicAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "Impersonation")]
        #pragma warning disable CS1591
        Impersonation,
        #pragma warning restore CS1591
        [EnumMember(Value = "MigratedSession")]
        #pragma warning disable CS1591
        MigratedSession,
        #pragma warning restore CS1591
    }
}
