// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>The error code identifying the type of error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserlandUsersControllerSendVerificationEmail0429_code
    {
        [EnumMember(Value = "daily_quota_exceeded")]
        #pragma warning disable CS1591
        Daily_quota_exceeded,
        #pragma warning restore CS1591
    }
}
