// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserlandUserInvitesControllerAccept400_code
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "invite_not_pending")]
        #pragma warning disable CS1591
        Invite_not_pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_invite")]
        #pragma warning disable CS1591
        Invalid_invite,
        #pragma warning restore CS1591
        [EnumMember(Value = "invite_has_accepted_user_id")]
        #pragma warning disable CS1591
        Invite_has_accepted_user_id,
        #pragma warning restore CS1591
    }
}
