// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Distinguishes the Waitlist object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WaitlistObject
    {
        [EnumMember(Value = "waitlist")]
        #pragma warning disable CS1591
        Waitlist,
        #pragma warning restore CS1591
    }
}
