// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Models
{
    /// <summary>Distinguishes the Webhook Endpoint object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WebhookEndpointObject
    {
        [EnumMember(Value = "webhook_endpoint")]
        #pragma warning disable CS1591
        WebhookEndpoint,
        #pragma warning restore CS1591
    }
}
