// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Radar.Attempts
{
    /// <summary>The action being performed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AttemptsPostRequestBody_action
    {
        [EnumMember(Value = "login")]
        #pragma warning disable CS1591
        Login,
        #pragma warning restore CS1591
        [EnumMember(Value = "signup")]
        #pragma warning disable CS1591
        Signup,
        #pragma warning restore CS1591
        [EnumMember(Value = "sign-in")]
        #pragma warning disable CS1591
        SignIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "sign_up")]
        #pragma warning disable CS1591
        Sign_up,
        #pragma warning restore CS1591
        [EnumMember(Value = "sign_in")]
        #pragma warning disable CS1591
        Sign_in,
        #pragma warning restore CS1591
    }
}
