// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.WorkOs.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \feature-flags\{slug}\targets\{resourceId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithResourceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.Item.WithResourceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/feature-flags/{slug}/targets/{resourceId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.Item.WithResourceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/feature-flags/{slug}/targets/{resourceId}", rawUrl)
        {
        }
        /// <summary>
        /// Removes a target from the feature flag&apos;s target list in the current environment. Currently, supported targets include users and organizations.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerDeleteTarget400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerDeleteTarget403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerDeleteTarget404">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerDeleteTarget400.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerDeleteTarget403.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerDeleteTarget404.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Enables a feature flag for a specific target in the current environment. Currently, supported targets include users and organizations.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerCreateTarget400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerCreateTarget403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerCreateTarget404">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerCreateTarget400.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerCreateTarget403.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.WorkOs.OpenApiClient.Models.FlagTargetsControllerCreateTarget404.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Removes a target from the feature flag&apos;s target list in the current environment. Currently, supported targets include users and organizations.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Enables a feature flag for a specific target in the current environment. Currently, supported targets include users and organizations.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.Item.WithResourceItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.Item.WithResourceItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.Item.WithResourceItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
