// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets
{
    /// <summary>
    /// Builds and executes requests for operations under \feature-flags\{slug}\targets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TargetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.WorkOs.OpenApiClient.featureFlags.item.targets.item collection</summary>
        /// <param name="position">The resource ID in format &quot;user_&lt;id&gt;&quot; or &quot;org_&lt;id&gt;&quot;.</param>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.Item.WithResourceItemRequestBuilder"/></returns>
        public global::Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.Item.WithResourceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("resourceId", position);
                return new global::Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.Item.WithResourceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.TargetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TargetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/feature-flags/{slug}/targets", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.FeatureFlags.Item.Targets.TargetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TargetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/feature-flags/{slug}/targets", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
