// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.WorkOs.OpenApiClient.Connect.Applications;
using Soenneker.WorkOs.OpenApiClient.Connect.Client_secrets;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Connect
{
    /// <summary>
    /// Builds and executes requests for operations under \connect
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConnectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The applications property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Connect.Applications.ApplicationsRequestBuilder Applications
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.Connect.Applications.ApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The client_secrets property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Connect.Client_secrets.Client_secretsRequestBuilder Client_secrets
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.Connect.Client_secrets.Client_secretsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Connect.ConnectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConnectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/connect", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Connect.ConnectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConnectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/connect", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
