// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.Check;
using Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.Resources;
using Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.Role_assignments;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \authorization\organization_memberships\{organization_membership_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOrganization_membership_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The check property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.Check.CheckRequestBuilder Check
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.Check.CheckRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resources property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.Resources.ResourcesRequestBuilder Resources
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.Resources.ResourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The role_assignments property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.Role_assignments.Role_assignmentsRequestBuilder Role_assignments
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.Role_assignments.Role_assignmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.WithOrganization_membership_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganization_membership_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/authorization/organization_memberships/{organization_membership_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.WithOrganization_membership_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganization_membership_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/authorization/organization_memberships/{organization_membership_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
