// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.WorkOs.OpenApiClient.User_management.Users.Item.Email_verification.Confirm;
using Soenneker.WorkOs.OpenApiClient.User_management.Users.Item.Email_verification.Send;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.WorkOs.OpenApiClient.User_management.Users.Item.Email_verification
{
    /// <summary>
    /// Builds and executes requests for operations under \user_management\users\{-id}\email_verification
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Email_verificationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The confirm property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.User_management.Users.Item.Email_verification.Confirm.ConfirmRequestBuilder Confirm
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.User_management.Users.Item.Email_verification.Confirm.ConfirmRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The send property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.User_management.Users.Item.Email_verification.Send.SendRequestBuilder Send
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.User_management.Users.Item.Email_verification.Send.SendRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.User_management.Users.Item.Email_verification.Email_verificationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Email_verificationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user_management/users/{%2Did}/email_verification", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.User_management.Users.Item.Email_verification.Email_verificationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Email_verificationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user_management/users/{%2Did}/email_verification", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
