// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.WorkOs.OpenApiClient.DataIntegrations.Item.Authorize;
using Soenneker.WorkOs.OpenApiClient.DataIntegrations.Item.Token;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.WorkOs.OpenApiClient.DataIntegrations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \data-integrations\{slug}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSlugItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authorize property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.DataIntegrations.Item.Authorize.AuthorizeRequestBuilder Authorize
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.DataIntegrations.Item.Authorize.AuthorizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.DataIntegrations.Item.Token.TokenRequestBuilder Token
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.DataIntegrations.Item.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.DataIntegrations.Item.WithSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSlugItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data-integrations/{slug}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.DataIntegrations.Item.WithSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSlugItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data-integrations/{slug}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
