// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.WorkOs.OpenApiClient.Audit_logs.Actions;
using Soenneker.WorkOs.OpenApiClient.Audit_logs.Events;
using Soenneker.WorkOs.OpenApiClient.Audit_logs.Exports;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Audit_logs
{
    /// <summary>
    /// Builds and executes requests for operations under \audit_logs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Audit_logsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The actions property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Audit_logs.Actions.ActionsRequestBuilder Actions
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.Audit_logs.Actions.ActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Audit_logs.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.Audit_logs.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exports property</summary>
        public global::Soenneker.WorkOs.OpenApiClient.Audit_logs.Exports.ExportsRequestBuilder Exports
        {
            get => new global::Soenneker.WorkOs.OpenApiClient.Audit_logs.Exports.ExportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Audit_logs.Audit_logsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Audit_logsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/audit_logs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Audit_logs.Audit_logsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Audit_logsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/audit_logs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
