// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships
{
    /// <summary>
    /// Builds and executes requests for operations under \authorization\organization_memberships
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Organization_membershipsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.WorkOs.OpenApiClient.authorization.organization_memberships.item collection</summary>
        /// <param name="position">The ID of the organization membership to check.</param>
        /// <returns>A <see cref="global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.WithOrganization_membership_ItemRequestBuilder"/></returns>
        public global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.WithOrganization_membership_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("organization_membership_id", position);
                return new global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Item.WithOrganization_membership_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Organization_membershipsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Organization_membershipsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/authorization/organization_memberships", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.WorkOs.OpenApiClient.Authorization.Organization_memberships.Organization_membershipsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Organization_membershipsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/authorization/organization_memberships", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
